name: issue_to_notion
on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notion Card Creator
        uses: dodo4114/issue-to-notion@v1.1.1
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_URL: "https://www.notion.so/nouswong/github-issues-6ae16e2c3e42434ab58ba72d5f2ff5dd"
          PROPERTY_NAME : "status"
          STATE_OPEN : "open"
          STATE_CLOSED : "closed"
